### PR TITLE
Space saving

### PR DESCRIPTION
**Pull request by jhtpotter**
Added a new Nextflow process to delete the following sets of intermediate readfiles after the Subsampling process has finished:
1. fastp-trimmed reads in Nextflow $WORK
2. copy of fastp-trimmed reads in $HOME
3. copy of subsampled reads in $HOME

These 3 sets of readfiles are not needed beyond this stage. Only the subsampled reads in Nextflow $WORK are used by the pipeline after this step.

Also did some general Nextflow formatting :)

### CODE REVIEW

**Comment by jhtpotter** [comment]
touch and > at the start of a line are pretty synonymous, but I think touch is a little less confusing!

**Comment by JaromirGuzinski** [comment]
> touch and > at the start of a line are pretty synonymous, but I think touch is a little less confusing!

Thanks!

**Comment by afishman** [comment]
> Presumably the build step failing are more kinks which need ironing out in TeamCity? @afishman

Urrrghh yeah TeamCity being inconsistent with how it is checking out branches. - which is what I've been using to name tag docker images

I'm using the git sha now, so hopefully that will be consistent. 

I've re-run your job so hopefully that'll pass now

**Comment by jhtpotter** [comment]
> > Presumably the build step failing are more kinks which need ironing out in TeamCity? @afishman
> 
> Urrrghh yeah TeamCity being inconsistent with how it is checking out branches. - which is what I've been using to name tag docker images
> 
> I'm using the git sha now, so hopefully that will be consistent.
> 
> I've re-run your job so hopefully that'll pass now

There appears to still be an issue with Docker? Most of this is still way over my head. Sorry I can't be much help!

_invalid argument "jguzinski/salmonella-seq:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
invalid reference format
Process exited with code 1_

**Comment by afishman** [comment]
> > > Presumably the build step failing are more kinks which need ironing out in TeamCity? @afishman
> > 
> > 
> > Urrrghh yeah TeamCity being inconsistent with how it is checking out branches. - which is what I've been using to name tag docker images
> > I'm using the git sha now, so hopefully that will be consistent.
> > I've re-run your job so hopefully that'll pass now
> 
> There appears to still be an issue with Docker? Most of this is still way over my head. Sorry I can't be much help!
> 
> _invalid argument "jguzinski/salmonella-seq:" for "-t, --tag" flag: invalid reference format See 'docker build --help'. invalid reference format Process exited with code 1_

Yeah the issue is that sometimes, TeamCity decides to do a checkout the commit of the PR into a detached HEAD state - i.e not on a branch. This causes the branch name to be blank and then the Docker tag name to be invalid (as it was named by branch).  poop

**Comment by afishman** [comment]
> > > > Presumably the build step failing are more kinks which need ironing out in TeamCity? @afishman
> > > 
> > > 
> > > Urrrghh yeah TeamCity being inconsistent with how it is checking out branches. - which is what I've been using to name tag docker images
> > > I'm using the git sha now, so hopefully that will be consistent.
> > > I've re-run your job so hopefully that'll pass now
> > 
> > 
> > There appears to still be an issue with Docker? Most of this is still way over my head. Sorry I can't be much help!
> > _invalid argument "jguzinski/salmonella-seq:" for "-t, --tag" flag: invalid reference format See 'docker build --help'. invalid reference format Process exited with code 1_
> 
> Yeah the issue is that sometimes, TeamCity decides to do a checkout the commit of the PR into a detached HEAD state - i.e not on a branch. This causes the branch name to be blank and then the Docker tag name to be invalid (as it was named by branch). poop

look slike it is running now, I've changed it to so images are tagged by SHA rather than branch name, which should be yield the same value in detached HEAD states.

**Comment by jhtpotter** [comment]
Awesome, everything passed

**Pull request merged**
